name: CheckPython
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
      - name: Run a one-line script
        run: python -V
