name: Generate PowerPoint Course Request with Lupo (v3)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Execute Lupo Action
        run: |
          curl -L -X POST http://20.55.39.142:5000/api/action \
          -H "Content-Type: application/json" \
          -d '{"repo":"'$repo'","branch":"'$branch'","actor":"'$actor'","lupo_version":"pptx_create_request_v3"}'
        env:
          repo: ${{ github.repository }}
          branch: ${{ github.ref }}
          actor: ${{ github.actor }}