name: Generate Course
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      token: '${{ secrets.LUPO_ACCESS_TOKEN_2023 }}'
      repo: '${{ github.repository }}'
      branch: 'main'
      repo_private_key: ''
      actor: ${{ github.actor }}
    steps:
      - name: Modify the variable
        id: modify_variable
        run: |
          # Replace '-' with '_' and convert to uppercase
          modified_variable=$(echo "${{ env.original_variable }}" | tr '-' '_' | tr '[:lower:]' '[:upper:]')
          echo $modified_variable
      # Assign the modified variable to the environment variable
      - name: Set modified variable
        run: |
          echo "modified_variable=${{ steps.modify_variable.outputs.stdout }}_PRIVATE_KEY" >> $GITHUB_ENV
      - name: Who executes this
        run: |
          echo $token
          echo $repo
          echo $branch
          echo $repo_private_key
          echo $actor
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $token" \
          https://api.github.com/repos/MLGuru-ai/course-creator/actions/workflows/course-creation-v2.yml/dispatches \
          -d '{"ref":"main","inputs":{"repo":"'$repo'","branch":"'$branch'","repo_private_key":"'$repo_private_key'","actor":"'$actor'"}}'
