name: Generate Course
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      token: '${{secrets.LUPO_ACCESS_TOKEN_2023}}'
      repo: 'Lupo-AI/hello-world'
      branch: 'main'
      repo_private_key: 'HELLO_WORLD_PRIVATE_KEY'
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $token" \
          https://api.github.com/repos/MLGuru-ai/course-creator/actions/workflows/course-creation.yml/dispatches \
          -d '{"ref":"main","inputs":{"repo":"'$repo'","branch":"'$branch'","repo_private_key":"'$repo_private_key'"}}'
